"""
Bronze Layer — Structured Data Ingestion (CSV, Parquet → Delta).
Ingests raw CSV/Parquet files into Delta tables with no transformations.

TRAINEE GUIDE — What is the Bronze Layer?
The Bronze layer is the FIRST stop for all incoming data. It is the "raw
landing zone" of the Medallion Architecture:

  Raw Files → [Bronze] → Silver → Gold

Key rules for Bronze:
  1. NO business transformations. Data lands exactly as it was received.
  2. ALL columns stored as strings for CSV (even numbers and dates). This is
     called "schema-on-read" — we defer type interpretation to Silver.
  3. Metadata columns are added to every row (_ingestion_timestamp, _batch_id,
     _source_file, _source_format) to enable full audit traceability.
  4. Tables are overwritten on every run (idempotent / safe to re-run).

Why keep raw data?
  - If Silver or Gold transformations have a bug, you can reprocess from Bronze
    without re-downloading the original files.
  - Auditors can compare Silver/Gold outputs against the original Bronze data
    to verify no data was altered unexpectedly.
  - It preserves the exact source data for forensic investigation.

This module handles STRUCTURED formats (CSV and Parquet).
For JSON and XML, see ingest_semi_structured.py.

Usage (Databricks):
    from src.bronze.ingest_structured import BronzeStructuredIngestion
    ingestion = BronzeStructuredIngestion(spark)
    ingestion.ingest_all()
"""

from pyspark.sql import SparkSession
from src.common.utils import add_metadata_columns, write_delta_table

# TRAINEE NOTE — Constants at the top of each file
# CATALOG and SCHEMA are defined once here so that if the catalog or schema
# name ever changes, you only need to update it in one place (not scattered
# across many function calls). This is the "DRY" principle: Don't Repeat Yourself.
CATALOG = "insurance_catalog"
SCHEMA = "bronze"


class BronzeStructuredIngestion:
    """Ingest structured (CSV/Parquet) files into Bronze Delta tables.

    TRAINEE NOTE — Why a class instead of standalone functions?
    Using a class lets us pass the SparkSession once (in __init__) and reuse
    it across all methods, rather than passing it as an argument to every
    function call. It also groups related methods together logically.
    """

    def __init__(self, spark: SparkSession, raw_base_path: str = "/Volumes/insurance_catalog/bronze/raw_data"):
        self.spark = spark
        # raw_base is the root folder in cloud storage (ADLS/S3/GCS) where
        # all raw source files are dropped before ingestion.
        self.raw_base = raw_base_path

    def ingest_all(self):
        """Ingest all structured data sources into Bronze layer.

        TRAINEE NOTE — The ingestion_map pattern
        Instead of writing one function per table (which would be repetitive),
        we define a list of tuples that describe all sources:
          (path_suffix, target_table_name, file_format)

        We then loop over the list and call _ingest_source() for each entry.
        This makes it easy to add a new data source — just add a new tuple
        to ingestion_map without writing any new code.

        The try/except around each ingestion ensures that if one source file
        is missing or corrupt, the pipeline SKIPS it and continues with the
        next source, rather than crashing entirely. This is called "graceful
        degradation" — the pipeline is resilient to partial failures.
        """
        print("=" * 60)
        print("Bronze Layer — Structured Data Ingestion")
        print("=" * 60)

        # Each tuple: (relative path under raw_base, target Delta table name, format)
        ingestion_map = [
            # Property insurance: synthetic data (generated by us) + FEMA public data
            ("property/synthetic_policies_csv", "bronze_property_policies_csv", "csv"),
            ("property/synthetic_claims_csv", "bronze_property_claims_csv", "csv"),
            ("property/fema_nfip_claims_bulk", "bronze_property_fema_claims_csv", "csv"),   # FEMA bulk download
            ("property/fema_nfip_policies_bulk", "bronze_property_fema_policies_csv", "csv"),
            # Workers' Compensation: policies only (claims are JSON — see semi-structured)
            ("workers_comp/synthetic_policies_csv", "bronze_workers_comp_policies_csv", "csv"),
            # Auto: policies and claims in CSV form
            ("auto/synthetic_policies_csv", "bronze_auto_policies_csv", "csv"),
            ("auto/synthetic_claims_csv", "bronze_auto_claims_csv", "csv"),
            # General Liability: policies only (claims are JSON)
            ("general_liability/synthetic_policies_csv", "bronze_general_liability_policies_csv", "csv"),
            # Umbrella: both policies and claims
            ("umbrella/synthetic_policies_csv", "bronze_umbrella_policies_csv", "csv"),
            ("umbrella/synthetic_claims_csv", "bronze_umbrella_claims_csv", "csv"),
        ]

        for source_suffix, table_name, fmt in ingestion_map:
            source_path = f"{self.raw_base}/{source_suffix}"
            try:
                self._ingest_source(source_path, table_name, fmt)
            except Exception as e:
                # WARN (not ERROR): we log the issue but continue the loop.
                # Missing source files are expected during partial test runs.
                print(f"  WARN: Skipping {table_name} — {str(e)}")

        print("\nBronze structured ingestion complete.")

    def _ingest_source(self, source_path: str, table_name: str, fmt: str):
        """Ingest a single structured source into a Bronze Delta table.

        TRAINEE NOTE — Three key decisions in this method:

        1. inferSchema=false (CSV only)
           By default Spark "infers" column types by scanning the file.
           We disable this and read every column as a string. Why?
             - Inference is not reliable: a column with mostly integers but
               one "N/A" value will be inferred as string anyway.
             - We want Silver to own type casting — Bronze just lands raw data.
             - Reading as strings is faster (no second scan needed).
           For Parquet, types are embedded in the file format itself, so we
           read Parquet with its native types preserved.

        2. multiLine=true + escape='"' (CSV)
           Insurance data often has fields with embedded commas or newlines
           (e.g. a description field). multiLine allows record values to span
           multiple lines. escape='"' tells Spark that double-quotes inside
           quoted fields are escaped with another double-quote (standard CSV).

        3. mode="overwrite" (Delta write)
           We overwrite the entire Bronze table on every run. This ensures
           the table always reflects the latest source file. It is safe to
           re-run because the output is deterministic given the same input
           (idempotent operation).
        """
        print(f"\n  Ingesting: {table_name}")
        print(f"    Source: {source_path}")

        # Read raw data — all columns as strings for CSV (schema-on-read)
        if fmt == "csv":
            df = (
                self.spark.read.option("header", "true")        # First row is column names
                .option("inferSchema", "false")                  # Keep everything as string
                .option("multiLine", "true")                     # Allow newlines inside fields
                .option("escape", '"')                           # Handle quoted commas
                .csv(source_path)
            )
        elif fmt == "parquet":
            # Parquet is a binary columnar format that already stores type info.
            # No options needed — Spark reads types correctly from the file schema.
            df = self.spark.read.parquet(source_path)
        else:
            raise ValueError(f"Unsupported format: {fmt}")

        # Add metadata columns for audit trail (see utils.py for explanation)
        df = add_metadata_columns(df, source_file=source_path, source_format=fmt)

        # Write to Delta table in Unity Catalog — overwrite to keep it idempotent
        write_delta_table(
            df=df,
            catalog=CATALOG,
            schema=SCHEMA,
            table=table_name,
            mode="overwrite",
        )

        # Print row count for monitoring — helps catch empty files or partial loads
        row_count = df.count()
        print(f"    Rows: {row_count:,}")
        print(f"    Table: {CATALOG}.{SCHEMA}.{table_name}")

    def ingest_single(self, source_path: str, table_name: str, fmt: str = "csv"):
        """Ingest a single file/directory into a Bronze Delta table.

        TRAINEE NOTE:
        This is a public convenience method for ad-hoc ingestion outside of
        the standard pipeline run. For example, if a new one-off file arrives
        from a business partner, you can call this directly from a notebook
        without modifying ingest_all().
        """
        self._ingest_source(source_path, table_name, fmt)
